// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/btachon-directions/Cinematic.tsx": () => import("../components/mockups/btachon-directions/Cinematic.tsx"),
  "./components/mockups/btachon-directions/Editorial.tsx": () => import("../components/mockups/btachon-directions/Editorial.tsx"),
  "./components/mockups/btachon-directions/Mosaic.tsx": () => import("../components/mockups/btachon-directions/Mosaic.tsx")
};
